# Generated by Django 3.2.18 on 2023-04-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20)),
                ('shard', models.IntegerField()),
                ('prirep', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('docs', models.IntegerField()),
                ('store', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('node', models.CharField(max_length=20)),
            ],
        ),
    ]
